### ISSUE TITLE
Readme updates

### ISSUE THREAD

**Issue by jacopotarantino** [behance/focss#17]
Hi, I just came across this repo and it seems really useful but I had a lot of trouble getting started with it. The tagline description got me interested but it would be really helpful if the readme had details on how to do common operations that would help new developers hit the ground running. Some questions that I had and try to answer in other readmes:

* How do I install this?
* What are any dependencies of the project?
* How do I run the tests to make sure the code is working right?
* How do I consume this module?
* How can I contribute back to the project?

If anybody could help me fill these in I'd really appreciate it.

**Comment by kaicataldo** [comment]
Hey @jacopotarantino, this repository is currently unmaintained - thanks for your interest and apologies for the late reply!
